### ISSUE TITLE
Abou testvis usage

### ISSUE THREAD

**Issue by 0x04C2** [shanhuio/tools#2]
Hi, @h8liu 

I have "Watch" on shanhuio for a while. The visualizing tool make the code like novel. It is very awesome, because it is easy to know the dependency. Cool thing.

I try to use testvis to visualize my go project. But it seems that the functionality is not as complete as the shanhuio/smlvm. I'm not "伸手党" and want to know whether there is a full functional tool about dagvis. If it is open-source, it will be great.

I'm looking forward to your reply. :)

**Comment by yumuzi234** [comment]
Hello, @0x04C2 

h8liu is a little busy recently, so let me answer your questions.

testvis is an earlier prototype that renders a DAG file, and we are building a Web service that generates golang package level dependency for any Go project. It will be quite useful, right? Could you tell us more detail what kind of visualization tool you want, what kind of project you are trying to maintain, to help us build such service. We can talk more through email: yumuzi234@gmail.com.  
 
If you would like to try something for now.
https://github.com/shanhuio/tools/blob/master/testvis/dag.js contains the data, which is a json file of a DAG. To generate the json file, you may need to change https://github.com/shanhuio/tools/blob/master/cmd/smldag/main.go a little bit.

**Comment by 0x04C2** [comment]
Thank you @yumuzi234 !

I send the detail to your email. Please take a look, thanks.

**Comment by h8liu** [comment]
hi @0x04C2, how's stuff?

per discussion in email, are you still working on fixing the issue of vender packages. If not, I might have a look by myself. thanks.

**Comment by 0x04C2** [comment]
Hi @h8liu 

My apology! I have done something here. But I forgot to update here.

When we list packages in one path, we can add `strings.HasPrefix(base, "vendor")` into the `goload/list_pkgs.go` to skip vendor folder. It is easy. 

However, I still have trouble here. The repo uses "shanhuio/tools", but I think that it should be "github.com/shanhuio/tools". This is why that I don't make PR. The diff is here.

```
diff --git a/cmd/pkgdag/main.go b/cmd/pkgdag/main.go
new file mode 100644
index 0000000..2a6b03c
--- /dev/null
+++ b/cmd/pkgdag/main.go
@@ -0,0 +1,41 @@
+package main
+
+import (
+       "flag"
+       "fmt"
+       "io/ioutil"
+       "os"
+
+       "github.com/shanhuio/tools/godep"
+       "github.com/shanhuio/tools/goload"
+       "shanhu.io/smlvm/dagvis"
+)
+
+func ne(e error) {
+       if e != nil {
+               fmt.Fprintln(os.Stderr, e)
+               os.Exit(-1)
+       }
+}
+
+func saveLayout(g *dagvis.Graph, f string) {
+       m, e := dagvis.LayoutJSON(g)
+       ne(e)
+
+       e = ioutil.WriteFile(f, m, 0644)
+       ne(e)
+}
+
+func main() {
+       path := flag.String("path", "e8vm.io/e8vm", "go pkg path to check")
+       flag.Parse()
+
+       pkgs, err := goload.ListPkgs(*path)
+       fmt.Println(pkgs)
+       ne(err)
+
+       pkgDag, err := godep.PkgDep(pkgs)
+       ne(err)
+
+       saveLayout(pkgDag, "dags/pkg.json")
+}
diff --git a/godep/file.go b/godep/file.go
index 5ad3faf..4987b74 100644
--- a/godep/file.go
+++ b/godep/file.go
@@ -10,8 +10,8 @@ import (

        "golang.org/x/tools/go/loader"

+       "github.com/shanhuio/tools/goload"
        "shanhu.io/smlvm/dagvis"
-       "shanhu.io/tools/goload"
 )

 // filename returns a file node name for a file
diff --git a/goload/list_pkgs.go b/goload/list_pkgs.go
index c632c5b..d6dd78e 100644
--- a/goload/list_pkgs.go
+++ b/goload/list_pkgs.go
@@ -43,7 +43,7 @@ func ListPkgs(p string) ([]string, error) {
                }
                base := filepath.Base(path)

-               if strings.HasPrefix(base, "_") || strings.HasPrefix(base, ".") {
+               if strings.HasPrefix(base, "_") || strings.HasPrefix(base, ".") || strings.HasPrefix(base, "vendor") {
                        return filepath.SkipDir
                }
```

Besides, the fileDep check is killing me.... Is there a way to skip fileDep check ?

**Comment by h8liu** [comment]
Thanks. I will take it here and integrate it in, and I will make filedep check optional. stay tuned.

for the import path, we use `shanhu.io/tools` for this repo (rather than `github.com/shanhuio/tools`. For example, you can `go get shanhu.io/tools`.

**Comment by h8liu** [comment]
hi, @0x04C2 

- the `vendor` issue should be fixed.
- I changed the `smldag` binary. now it accepts an argument which specifies the project folder and will output the dag layout.
- for example, you can `smldat -repo=shanhu.io/smlvm -out=testvis/dag.js` and then view dag of `smlvm` (you need to have the project downloaded and compilable first)

I tried `etcd` and `go-systemd` from coreos team:

`go-systemd` are mostly standalone packages that do not require each other (but requires packages under repo `coreos/pkg` instead). Also, it does not compile on mac osx because is uses cgo.

`etcd` also uses cgo, and has a non-standard compile procedure (i.e. cannot be installed via `go get` directly). Nevertheless, I can draw the DAG out, although the figure is pretty large.

Hope that helps a little bit.

**Comment by 0x04C2** [comment]
Hi @h8liu ! Thank you!!!

I'm using it. It's very cool. I'll give your feedback about this.

Waiting for your update about FileDep.

**Comment by h8liu** [comment]
The `smldag` utility does not do anything about the file deps. File deps requires files to be non-circular dependent, which is not true for most go programs.

**Comment by 0x04C2** [comment]
hi @h8liu , yes. smldag only outputs the pkgdeps. 

A lot of guys in our team are new gophers, including me. The pkgdep is very helpful to organize our package, not put all the code in one package.... I will introduce this tool to my teammate in this Friday CST. Hope this tool can be used by more and more gophers. :)

**Comment by h8liu** [comment]
thanks.
